{
    'name': 'Team Incident Management',
    'version': '18.0.0.0.1',
    'description': 'Manages incidents and their status',
    'summary': ' Manages incidents and their status',
    'author': 'Amnil Technologys',
    'website': 'www.amniltechnologies.com',
    'license': 'LGPL-3',
    'category': 'Productivity',
    'depends': [
        'base_setup',
        'mail',
        'hr',
        'project',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'wizard/incident_state_wizard.xml',
        'views/incident_team.xml',
        'views/incident_type.xml',
        'views/team_incidents.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}